const json=(data,status=200,extra={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8","access-control-allow-origin":extra.origin||"*","access-control-allow-credentials":"true","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS","access-control-allow-headers":"Content-Type,Authorization","vary":"Origin"}});
const now=()=>new Date().toISOString(),id=()=>crypto.randomUUID(),enc=new TextEncoder();
const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
async function digest(v){return b64(await crypto.subtle.digest("SHA-256",typeof v==="string"?enc.encode(v):v))}
async function passwordHash(password,salt){const key=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:typeof salt==="string"?enc.encode(salt):salt,iterations:120000,hash:"SHA-256"},key,256);return b64(bits)}
async function hashPassword(password){const salt=b64(crypto.getRandomValues(new Uint8Array(16)));return{salt,hash:await passwordHash(password,salt)}}
function same(a,b){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
function origin(req,env){return env.APP_ORIGIN||new URL(req.url).origin}
function headers(req,env){return{origin:origin(req,env)}}
function cookie(name,value,maxAge){return name+"="+value+"; Path=/; HttpOnly; Secure; SameSite=None; Max-Age="+maxAge}
function getCookie(req,name){const c=req.headers.get("Cookie")||"";for(const part of c.split(";")){const a=part.trim().split("=");if(a[0]===name)return a.slice(1).join("=")}return null}
async function userFrom(req,env){const token=getCookie(req,"nn_session")||req.headers.get("Authorization")?.replace(/^Bearer\s+/i,"");if(!token||!env.DB)return null;return await env.DB.prepare("SELECT u.id,u.email,u.name,u.company,u.verified,u.theme,u.created_at,u.updated_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?").bind(await digest(token),now()).first()}
const tables={projects:["name","description","status","budget"],clients:["name","email","company","status"],services:["name","description","price","status"],tasks:["title","status","priority","project_id","due_date"],transactions:["type","amount","description","transaction_date"]};
async function all(db,t,owner){return(await db.prepare("SELECT * FROM "+t+" WHERE owner_id=? ORDER BY created_at DESC").bind(owner).all()).results}
function clean(b,fields){const o={};for(const f of fields)if(b[f]!==undefined)o[f]=b[f];return o}
export default{async fetch(req,env){
const h=headers(req,env);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:{"access-control-allow-origin":h.origin,"access-control-allow-credentials":"true","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS","access-control-allow-headers":"Content-Type,Authorization","vary":"Origin"}});
const u=new URL(req.url),p=u.pathname.replace(/^\/|\/$/g,"").split("/").filter(Boolean);
try{
if(p[0]!=="api")return json({name:"NO-NAME API",version:"2.0.0",ok:true},200,h);
if(p[1]==="health")return json({ok:true,time:now()},200,h);
if(!env.DB)return json({error:"D1 binding DB is not configured"},503,h);
if(p[1]==="auth"){
const action=p[2];
if(req.method==="POST"&&action==="signup"){const b=await req.json(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||""),name=String(b.name||"").trim(),company=String(b.company||"").trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json({error:"Invalid email"},400,h);if(password.length<8)return json({error:"Password must be at least 8 characters"},400,h);if(!name)return json({error:"Name is required"},400,h);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"Email already registered"},409,h);const ph=await hashPassword(password),uid=id(),t=now();await env.DB.prepare("INSERT INTO users(id,email,name,company,password_hash,password_salt,verified,theme,created_at,updated_at) VALUES(?,?,?,?,?,?,0,'midnight',?,?)").bind(uid,email,name,company,ph.hash,ph.salt,t,t).run();const token=b64(crypto.getRandomValues(new Uint8Array(32))),exp=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)").bind(id(),uid,await digest(token),exp,t).run();return new Response(JSON.stringify({user:{id:uid,email,name,company,verified:false,theme:"midnight"},message:"Account created. Email verification can be connected later."}),{status:201,headers:{"content-type":"application/json","set-cookie":cookie("nn_session",token,2592000),...h}})}
if(req.method==="POST"&&action==="login"){const b=await req.json(),email=String(b.email||"").trim().toLowerCase(),password=String(b.password||""),u0=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!u0||!same(await passwordHash(password,u0.password_salt),u0.password_hash))return json({error:"Invalid email or password"},401,h);const token=b64(crypto.getRandomValues(new Uint8Array(32))),t=now(),exp=new Date(Date.now()+30*864e5).toISOString();await env.DB.prepare("INSERT INTO sessions(id,user_id,token_hash,expires_at,created_at) VALUES(?,?,?,?,?)").bind(id(),u0.id,await digest(token),exp,t).run();return new Response(JSON.stringify({user:{id:u0.id,email:u0.email,name:u0.name,company:u0.company,verified:!!u0.verified,theme:u0.theme}}),{headers:{"content-type":"application/json","set-cookie":cookie("nn_session",token,2592000),...h}})}
if(req.method==="POST"&&action==="logout"){const token=getCookie(req,"nn_session");if(token)await env.DB.prepare("DELETE FROM sessions WHERE token_hash=?").bind(await digest(token)).run();return new Response(JSON.stringify({ok:true}),{headers:{"content-type":"application/json","set-cookie":cookie("nn_session","",0),...h}})}
if(req.method==="GET"&&action==="me"){const me=await userFrom(req,env);return me?json({authenticated:true,user:me},200,h):json({authenticated:false},200,h)}
if(req.method==="PUT"&&action==="profile"){const me=await userFrom(req,env);if(!me)return json({error:"Unauthorized"},401,h);const b=await req.json(),name=String(b.name??me.name).trim(),company=String(b.company??me.company).trim(),theme=String(b.theme??me.theme);await env.DB.prepare("UPDATE users SET name=?,company=?,theme=?,updated_at=? WHERE id=?").bind(name,company,theme,now(),me.id).run();return json({ok:true,user:await userFrom(req,env)},200,h)}
if(req.method==="POST"&&action==="change-password"){const me=await userFrom(req,env);if(!me)return json({error:"Unauthorized"},401,h);const b=await req.json(),full=await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(me.id).first(),old=String(b.currentPassword||""),next=String(b.newPassword||"");if(!full||!same(await passwordHash(old,full.password_salt),full.password_hash))return json({error:"Current password is incorrect"},400,h);if(next.length<8)return json({error:"New password must be at least 8 characters"},400,h);const ph=await hashPassword(next);await env.DB.prepare("UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?").bind(ph.hash,ph.salt,now(),me.id).run();return json({ok:true},200,h)}
return json({error:"Not found"},404,h)}
if(p[1]==="dashboard"&&req.method==="GET"){const me=await userFrom(req,env);if(!me)return json({error:"Unauthorized"},401,h);const vals=await Promise.all(Object.keys(tables).map(t=>all(env.DB,t,me.id))),data={};Object.keys(tables).forEach((t,i)=>data[t]=vals[i]);const revenue=data.transactions.filter(x=>x.type==="income").reduce((a,x)=>a+x.amount,0),expenses=data.transactions.filter(x=>x.type==="expense").reduce((a,x)=>a+x.amount,0);return json({user:me,...data,metrics:{revenue,expenses,profit:revenue-expenses,projectCount:data.projects.length,clientCount:data.clients.length}},200,h)}
const table=p[1];if(!tables[table])return json({error:"Not found"},404,h);const me=await userFrom(req,env);if(!me)return json({error:"Unauthorized"},401,h);const rid=p[2];if(req.method==="GET"){if(rid){const r=await env.DB.prepare("SELECT * FROM "+table+" WHERE id=? AND owner_id=?").bind(rid,me.id).first();return r?json(r,200,h):json({error:"Not found"},404,h)}return json(await all(env.DB,table,me.id),200,h)}
if(req.method==="POST"){const b=await req.json(),data=clean(b,tables[table]);for(const f of tables[table])if(data[f]===undefined)return json({error:"Missing field: "+f},400,h);const r={id:id(),owner_id:me.id,...data,created_at:now(),updated_at:now()},cols=Object.keys(r);await env.DB.prepare("INSERT INTO "+table+" ("+cols.join(",")+") VALUES ("+cols.map(()=>"?").join(",")+")").bind(...cols.map(k=>r[k])).run();return json(r,201,h)}
if(req.method==="PUT"&&rid){const data=clean(await req.json(),tables[table]);data.updated_at=now();const set=Object.keys(data).map(k=>k+"=?").join(",");const r=await env.DB.prepare("UPDATE "+table+" SET "+set+" WHERE id=? AND owner_id=?").bind(...Object.values(data),rid,me.id).run();return r.meta.changes?json({id:rid,...data},200,h):json({error:"Not found"},404,h)}
if(req.method==="DELETE"&&rid){const r=await env.DB.prepare("DELETE FROM "+table+" WHERE id=? AND owner_id=?").bind(rid,me.id).run();return r.meta.changes?json({ok:true,id:rid},200,h):json({error:"Not found"},404,h)}
return json({error:"Method not allowed"},405,h)
}catch(e){return json({error:e.message},500,h)}}};